### ISSUE TITLE
Reduce CircleCI configuration complexity

### ISSUE THREAD

**Issue by renatomefi** [usabilla/php-docker-template#101]
## Context

CircleCI configuration can become really verbose and repetitive, here is a list of things that can be improved by either: Removing, downstream to Makefile, yaml anchors or CircleCI reusable commands

## The list

- This checks if all images were built: https://github.com/usabilla/php-docker-template/blob/615c9f77a26a5a54ac20eefc10ab173acf43defe/.circleci/config.yml#L213
- The whole build could be abstracted? https://github.com/usabilla/php-docker-template/blob/615c9f77a26a5a54ac20eefc10ab173acf43defe/.circleci/config.yml#L208
- Should Clair be running somewhere else? https://github.com/usabilla/php-docker-template/blob/615c9f77a26a5a54ac20eefc10ab173acf43defe/.circleci/config.yml#L176
- Others? Please comment

**Comment by rdohms** [comment]
Closed in favor of #151
