### ISSUE TITLE
Format PHP-FPM logs as JSON

### ISSUE THREAD

**Issue by rdohms** [usabilla/php-docker-template#152]
Currently PHP-FPM outputs to `stdout` and `stderr`, but it does so in its own single-line format which stops projects from adopting the `usabilla` format.

We should change their format to json and adhere to ADR-23.

Question: this is pretty opinionated for Usabilla, how do we separate from OSS?

**Comment by rdohms** [comment]
@renatomefi ideas on how to separate it?

Some interesting reads: http://www.inanzzz.com/index.php/post/6cn7/formatting-php-fpm-and-nginx-access-logs-as-standardised-json-string-in-docker-environment

**Comment by WyriHaximus** [comment]
@rdohms Given that we can configure the `access.format` mentioned at the bottom of that page, all we'd need to do it something like this at the bottom of: https://github.com/usabilla/php-docker-template/blob/master/src/php/fpm/conf/zz-docker.conf.template

```ini
access.format = ${PHP_FPM_ACCESS_FORMAT}
```

And add the following in the Dockerfile:

```Dockerfile
ENV PHP_FPM_ACCESS_FORMAT= "%R - %u %t \"%m %r\" %s"
```

(Which is the default format according to: https://www.php.net/manual/en/install.fpm.configuration.php)

**Comment by WyriHaximus** [comment]
Opened #153 implementing this.
