### ISSUE TITLE
Make GPG key download more reliable

### ISSUE THREAD

**Issue by frankkoornstra** [usabilla/php-docker-template#67]
Every time we have to install an extension, the GPG keys are downloaded and used. That fails more often than not so we need to find a way to make this more reliable.

The intermediate solution that is now implemented is that we cache the GPG keys (2 for each minor version) in the image itself. It'd be nicer if we could lift this to a higher level, maybe into GitLab?

**Comment by rdohms** [comment]
I believe this is no longer valid, can @stevenjm or @renatomefi confirm and close issue?

**Comment by renatomefi** [comment]
As we have downloaded it manually now for php 7.4, is that the expected process? should it be automated?

**Comment by carusogabriel** [comment]
@renatomefi I think so. Please see #64.

**Comment by renatomefi** [comment]
So should it be automated?

**Comment by renatomefi** [comment]
Like in the pipeline at least warning the key is wrong/missing, then someone can manually download it?

**Comment by frankkoornstra** [comment]
I'd happily live without this dependency (GPG servers) if we can. If you look at the cadence of releases for each PHP minor version, it's ok, it's not like we have to do this action every week, month or even quarter. We could create a Make target to automate the download and put it in the right place.

**Comment by renatomefi** [comment]
@frankkoornstra that's a good idea!
If we keep this open, we could translate into 2 objectives:
- Knowing when it's changed
- Having a local command to update it, then manual commit for security check!
