### ISSUE TITLE
Nodejs container

### ISSUE THREAD

**Issue by gabiudrescu** [usabilla/php-docker-template#82]
Given that in most modern apps nodejs is present through tools like webpack or various is linters, I would like to have that as an option for this stack setup.

**Comment by frankkoornstra** [comment]
The purpose of this repo is to provide a PHP container and an NGINX container that seamlessly connects to the FPM variant. If you're looking for NodeJS, I suggest taking a stroll through Docker Hub.

**Comment by gabiudrescu** [comment]
I see. I liked the way this repo was configured and I was thinking that maybe I'd be interested in creating a toolkit that includes most of the tools required for an average app. 

thanks anyway. 

and btw, good job, keep up!

**Comment by frankkoornstra** [comment]
Thanks, we're trying to do our best 😃

It really is geared towards the PHP needs we have internally but we think they're pretty generic so we're trying to contribute back to the community. We don't use a lot of Node (backend) internally but maybe if we do in the future, we'll make something similar.
