### ISSUE TITLE
Storage layer

### ISSUE THREAD

**Issue by gabiudrescu** [usabilla/php-docker-template#83]
Most of the time, you'll need a storage layer for your app: relational or non relational.

I'd make the assumption and say that probably, the most popular storage layers you'll find in the wild are MySQL and Redis. What about including them?

**Comment by frankkoornstra** [comment]
You're right and [Docker Compose](https://docs.docker.com/compose/overview/) gives you an excellent way of running a [MySQL](https://hub.docker.com/_/mysql) or [Redis](https://hub.docker.com/_/redis) container next to this PHP container. You can then, for example, point your Redis client to the other container by using the name of the service in the `docker-compose.yml`.

The general idea behind Docker is that containers do one thing really well. Using Docker Compose, you can combine all those containers.

**Comment by gabiudrescu** [comment]
I know. My suggestion was to add these containers in docker-compose.yml, but if you don't need them and if you don't plan to create from this repo a general dev toolkit, then this issue can be closed.

**Comment by frankkoornstra** [comment]
Good, sorry to assume you didn't 🙈 As mentioned in #82 the aim for now is to open source what we saw as generic enough internal containers. Thanks for the input!
