### ISSUE TITLE
Introduce PHP Prometheus Exporter image

### ISSUE THREAD

**Issue by renatomefi** [usabilla/php-docker-template#98]
## Context

Not every php process has a webserver which can expose prometheus metrics, thus a sidecar container can be a google solution for it.

## Possible solution

Just like JMX exporter works as a sidecar container, we can have a container which exposes the php metrics to be fetch by prometheus.

A Nginx container which takes a file with the metrics or that connects to php directly could achieve this.

As first option I'd say the file is the easiest to implement

**Comment by rdohms** [comment]
@renatomefi still valid?

**Comment by renatomefi** [comment]
Done via #99
